# Generated by Django 5.1.5 on 2025-02-05 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_question_source_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
    ]
