[tool.black]
line-length = 88  # Длина строки (по умолчанию 88)
target-version = ['py38', 'py39', 'py310']  # Поддерживаемые версии Python
include = '\.pyi?$'  # Форматируем только Python-файлы
exclude = '''
(
    /\..+  # Игнорируем ВСЕ файлы и папки, начинающиеся с точки (скрытые)
    | /migrations/  # Игнорируем папку миграций
)
'''