# Generated by Django 5.1.6 on 2025-02-19 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_tag_parents_alter_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='source',
            field=models.CharField(db_default='', default='', max_length=128, verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.TextField(db_default='', default='', verbose_name='Текст ответа'),
        ),
        migrations.AlterField(
            model_name='question',
            name='source',
            field=models.CharField(db_default='', default='', max_length=128, verbose_name='Источник'),
        ),
    ]
